// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARcQ8C5l5ceQtVb8pqAmVAI5MFuiKsHKg',
    appId: '1:881021244564:web:6961b2f0b09c47965fd081',
    messagingSenderId: '881021244564',
    projectId: 'songkhoe-qtt',
    authDomain: 'songkhoe-qtt.firebaseapp.com',
    storageBucket: 'songkhoe-qtt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQkIW3W8Ea8l4II_WfMT4NQQPVHN70fU',
    appId: '1:881021244564:android:cac878de148f501e5fd081',
    messagingSenderId: '881021244564',
    projectId: 'songkhoe-qtt',
    storageBucket: 'songkhoe-qtt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMnLO0961aruhzcWGDJHvxzRdr04RZWcI',
    appId: '1:881021244564:ios:48c29f9c740fafa45fd081',
    messagingSenderId: '881021244564',
    projectId: 'songkhoe-qtt',
    storageBucket: 'songkhoe-qtt.firebasestorage.app',
    iosBundleId: 'com.example.songkhoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMnLO0961aruhzcWGDJHvxzRdr04RZWcI',
    appId: '1:881021244564:ios:48c29f9c740fafa45fd081',
    messagingSenderId: '881021244564',
    projectId: 'songkhoe-qtt',
    storageBucket: 'songkhoe-qtt.firebasestorage.app',
    iosBundleId: 'com.example.songkhoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARcQ8C5l5ceQtVb8pqAmVAI5MFuiKsHKg',
    appId: '1:881021244564:web:5dee16693d122b885fd081',
    messagingSenderId: '881021244564',
    projectId: 'songkhoe-qtt',
    authDomain: 'songkhoe-qtt.firebaseapp.com',
    storageBucket: 'songkhoe-qtt.firebasestorage.app',
  );
}
